; Creates the program with fixed array in the code, like "data" section
; Then, computes sum of it. Address generated by label is passed to the summing procedure
; This is a simple example of self modifying code as well

JMP @begin
:data
5 4 3 2 1
:begin
PUSH 0 ; sum
PUSH 5 ; Array size
PUSH 0 ; counter
:loop
DUP ; copy of counter
EXTEND ; convert counter to 16 bit
PUSH16 @data ; base address
ADD16 ; ptr+counter
LOAD_GLOBAL ; *ptr
SYSCALL std.PrintInt
SYSCALL std.PrintNewLine
LOAD_LOCAL 0 ; sum
ADD
STORE_LOCAL 0
; Increment and check counter:
INC
DUP
LOAD_LOCAL 1
LESS_OR_EQ
JF @loop
LOAD_LOCAL 0 ; sum
SYSCALL std.PrintInt
SYSCALL std.PrintNewLine