; Byte a
; Byte x
PUSHN 2
MACRO_SET_LOCAL 0 4
MACRO_SET_LOCAL 0 8
MACRO_SET_LOCAL 0 0
MACRO_SET_LOCAL 0 4
MACRO_SET_LOCAL 0 2
MACRO_SET_LOCAL 0 2
MACRO_SET_LOCAL 0 2
MACRO_SET_LOCAL 0 4
MACRO_SET_LOCAL 1 2
LOAD_LOCAL 1 ; x
STORE_LOCAL 0 ; a
LOAD_LOCAL 1 ; x
MACRO_X2
STORE_LOCAL 0 ; a
MACRO_SET_LOCAL 0 0
MACRO_SET_LOCAL 0 0
MACRO_SET_LOCAL 0 0
MACRO_SET_LOCAL 0 12
HALT