; Byte arr[]
; Byte counter
; Addr arr2[]
PUSHN 5
PUSH_REG 1
STORE_LOCAL16 0 ; arr
PUSH 1
PUSH 2
PUSH 3
PUSH 4
PUSH 5
MACRO_SET_LOCAL 2 0
:while1_begin
LOAD_LOCAL 2 ; counter
PUSH 4
MACRO_CONDITIONAL_JF 5 @while1_endwhile
LOAD_LOCAL16 0 ; arr
LOAD_LOCAL 2 ; counter
MACRO_ADD8_TO_16
LOAD_GLOBAL
SYSCALL Std.PrintInt
POP
MACRO_INC_LOCAL 2 ;counter
JMP @while1_begin
:while1_endwhile
SYSCALL Std.PrintNewLine
PUSH_REG 1
STORE_LOCAL16 3 ; arr2
PUSH16 #1
PUSH16 #2
PUSH16 #3
PUSH16 #4
PUSH16 #5
MACRO_SET_LOCAL 2 0
:while2_begin
LOAD_LOCAL 2 ; counter
PUSH 4
MACRO_CONDITIONAL_JF 5 @while2_endwhile
LOAD_LOCAL16 0 ; arr
LOAD_LOCAL 2 ; counter
MACRO_ADD8_TO_16
LOAD_GLOBAL
SYSCALL Std.PrintInt
POP
MACRO_INC_LOCAL 2 ;counter
JMP @while2_begin
:while2_endwhile
SYSCALL Std.PrintNewLine
HALT